-- Example user (password should be bcrypt-hashed in application flow; this is illustrative only)
-- INSERT INTO users (name, email, password) VALUES ('Demo User', 'demo@example.com', '$2b$12$hash');
